FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY src/Portal.Application/Portal.Application.csproj ./Portal.Application/
RUN dotnet restore ./Portal.Application/Portal.Application.csproj
COPY src/ ./ 
RUN dotnet publish ./Portal.Application/Portal.Application.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Portal.Application.dll"]
